# Generated by Django 6.1.1 on 2026-10-05 16:35

import apps.ledger.models
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "icon",
                    models.CharField(
                        choices=apps.ledger.models.icon_choices, max_length=50
                    ),
                ),
                (
                    "colour",
                    models.CharField(
                        choices=apps.ledger.models.colour_choices, max_length=20
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": [django.db.models.functions.text.Lower("name")],
                "constraints": [
                    models.UniqueConstraint(
                        models.F("user"),
                        django.db.models.functions.text.Lower("name"),
                        name="unique_category_name_per_user",
                    )
                ],
            },
        ),
    ]
