# Generated by Django 6.1.1 on 2026-10-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="category",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
