# Each entry must be a Lucide icon in apps/ui/vendor.
ICONS = [
    ("bookmark", "Bookmark"),
    # Food and drink
    ("shopping-cart", "Shopping cart"),
    ("shopping-basket", "Shopping basket"),
    ("apple", "Apple"),
    ("carrot", "Carrot"),
    ("coffee", "Coffee"),
    ("cup-soda", "Soft drink"),
    ("beer", "Beer"),
    ("wine", "Wine"),
    ("utensils", "Cutlery"),
    ("pizza", "Pizza"),
    ("sandwich", "Sandwich"),
    ("ice-cream-cone", "Ice cream"),
    # Transport
    ("car", "Car"),
    ("car-taxi-front", "Taxi"),
    ("bus", "Bus"),
    ("train-front", "Train"),
    ("bike", "Bike"),
    ("fuel", "Fuel"),
    ("parking-meter", "Parking"),
    # Home
    ("house", "House"),
    ("building", "Building"),
    ("bed", "Bed"),
    ("sofa", "Sofa"),
    ("hammer", "Hammer"),
    ("wrench", "Wrench"),
    ("key-round", "Key"),
    # Bills
    ("zap", "Electricity"),
    ("droplet", "Water"),
    ("flame", "Gas"),
    ("wifi", "Internet"),
    ("smartphone", "Phone"),
    ("tv", "TV"),
    ("receipt", "Receipt"),
    ("file-text", "Document"),
    ("landmark", "Bank"),
    # Health
    ("heart-pulse", "Health"),
    ("pill", "Medicine"),
    ("stethoscope", "Doctor"),
    ("hospital", "Hospital"),
    ("dumbbell", "Fitness"),
    # Shopping
    ("shopping-bag", "Shopping bag"),
    ("shirt", "Clothing"),
    ("gem", "Jewellery"),
    ("scissors", "Haircut"),
    ("sparkles", "Beauty"),
    ("store", "Store"),
    ("package", "Package"),
    ("tag", "Tag"),
    # Entertainment
    ("film", "Film"),
    ("music", "Music"),
    ("gamepad-2", "Games"),
    ("ticket", "Ticket"),
    ("book-open", "Books"),
    ("headphones", "Headphones"),
    ("popcorn", "Popcorn"),
    ("palette", "Art"),
    # Income
    ("briefcase", "Work"),
    ("banknote", "Cash"),
    ("wallet", "Wallet"),
    ("coins", "Coins"),
    ("hand-coins", "Payment"),
    ("circle-dollar-sign", "Money"),
    ("laptop", "Laptop"),
    # Savings
    ("piggy-bank", "Savings"),
    ("trending-up", "Investments"),
    ("credit-card", "Credit card"),
    ("percent", "Interest"),
    ("shield", "Insurance"),
    ("umbrella", "Rainy day"),
    # Travel
    ("plane", "Flight"),
    ("luggage", "Luggage"),
    ("map", "Map"),
    ("tent", "Camping"),
    ("globe", "Globe"),
    # Kids
    ("baby", "Baby"),
    ("toy-brick", "Toys"),
    ("graduation-cap", "Education"),
    ("school", "School"),
    # Pets
    ("dog", "Dog"),
    ("cat", "Cat"),
    ("paw-print", "Pets"),
    # Other
    ("gift", "Gift"),
    ("heart", "Heart"),
    ("hand-heart", "Charity"),
    ("users", "Family"),
    ("calendar", "Calendar"),
]

# Literal class strings so Tailwind's source scanner emits them.
PALETTE = {
    "red": "text-red-600 dark:text-red-400",
    "orange": "text-orange-600 dark:text-orange-400",
    "amber": "text-amber-600 dark:text-amber-400",
    "yellow": "text-yellow-600 dark:text-yellow-400",
    "lime": "text-lime-600 dark:text-lime-400",
    "green": "text-green-600 dark:text-green-400",
    "emerald": "text-emerald-600 dark:text-emerald-400",
    "teal": "text-teal-600 dark:text-teal-400",
    "cyan": "text-cyan-600 dark:text-cyan-400",
    "sky": "text-sky-600 dark:text-sky-400",
    "blue": "text-blue-600 dark:text-blue-400",
    "indigo": "text-indigo-600 dark:text-indigo-400",
    "violet": "text-violet-600 dark:text-violet-400",
    "purple": "text-purple-600 dark:text-purple-400",
    "pink": "text-pink-600 dark:text-pink-400",
    "rose": "text-rose-600 dark:text-rose-400",
}

COLOURS = [(key, key.capitalize()) for key in PALETTE]
